### ISSUE TITLE
Change design for "content first"

### ISSUE THREAD

**Issue by AmaroNeto** [DiscordTime/sticky-sessions-android#130]
source:

https://medium.com/amazing-stuff/complexion-reduction-a-new-trend-in-mobile-design-cef033a0b978

https://medium.com/@8obbyanderson/change-your-focus-and-design-content-first-a124e12f3bb2

https://blog.prototypr.io/importance-of-white-space-in-design-5a40c0e65bfd

**Comment by rodrigoperazzo** [comment]
Related to #152

**Comment by rodrigoperazzo** [comment]
As part of this effort, we could pull available sessions to the first screen below creation options.

**Comment by rodrigoperazzo** [comment]
There are few designers being included on the team. They should decide that.
