### ISSUE TITLE
Implement long press on session list to change time when session is going to happen

### ISSUE THREAD

**Issue by viniciusalbuquerque** [DiscordTime/sticky-sessions-android#145]
Until now, we were assuming the time of creation was the time when the Session was happening. We need to implement a way of defining the date that the Session is happening so we can open the Session for future dates.

**Comment by rodrigoperazzo** [comment]
@viniciusalbuquerque  Changed issue title based on the conversation we had earlier today. It is much easier to implement as is described now than trying to implement a new flow or change current flow from lobby activity to session activity.
