### ISSUE TITLE
Rename Session related variable(s) from seconds to milliseconds

### ISSUE THREAD

**Issue by rodrigoperazzo** [DiscordTime/sticky-sessions-android#168]
A variable on SessionMapper has a name with the "seconds" term but it in practice represents the milliseconds part of the creation date of a Session object. 

We should check by other places in the code which might be using the wrong term too.

**Comment by VitorPoncell** [comment]
Fixed in 98e1793ab025a980c1ea9927caaf61fa9d37ae37
