### ISSUE TITLE
Transform user dialog into a Login Activity

### ISSUE THREAD

**Issue by viniciusalbuquerque** [DiscordTime/sticky-sessions-android#79]
User activity should be the Main Activity of the app.

**Comment by rodrigoperazzo** [comment]
Comment made on create teams issue:

[ ] Change LoginActivity to receive an email and an name. This activity will now be open when the user clicks on Join Session or when he clicks in a shared link
[ ] Change ListSession use case to send the user email to receive the sessions of his team
[ ] Change SessionRemote model to have an team attribute
[ ] Create ListTeams use case. Should list all teams a user is registered, So he can choose one of them when creating an session
[ ] Change CreateSession use case to send the chosen user's team
[ ] Change EnterSession use case to send the user's email, to verify if he have the right to enter in that team's session
[ ] Create a EditName use case
[ ] Create a Logout use Case

**Comment by rodrigoperazzo** [comment]
Too broad. We should create small features.
